version: '3'

services:
  redis:
    image: redis
    container_name: nvr-redis
    restart: always
    expose:
      - '6379'
    network_mode: host

  backend:
    depends_on:
      - redis
    build: ./backend
    container_name: nvr-backend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
      - ~/creds:/creds
    expose:
      - '5000'
      - '5001'
      - '5002'
    network_mode: host
    
  video_backend:
    build: ./file_uploader
    container_name: file_uploader
    restart: always
    volumes:
      - ./file_uploader:/file_uploader
      - ~/creds:/creds
    expose:
      - '5005'
    network_mode: host  

  frontend:
    build:
      context: ./frontend
      # непонел как ещё передать переменную окружения на этап билда
      args:
        NVR_CLIENT_URL: https://nvr.miem.hse.ru
    container_name: nvr-frontend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
    expose:
      - '80'
    network_mode: host

