version: '3'
services:
  redis:
    image: redis
    container_name: nvr-redis
    expose:
      - '6379'
    network_mode: host

  app:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        NVR_CLIENT_URL: https://nvr.miem.hse.ru
    container_name: nvr-app
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
      - ~/creds:/creds
    expose:
      - '5000'
    network_mode: host

  fileuploader:
    depends_on:
      - redis
    build: ./fileuploader
    container_name: nvr-fileuploader
    volumes:
      - ./fileuploader:/fileuploader
      - ~/creds:/creds
    expose:
      - '5500'
    network_mode: host
