version: '3'

services:
  redis:
    image: redis
    container_name: nvr-redis
    restart: always
    expose:
      - '6379'
    network_mode: host

  backend:
    depends_on:
      - redis
    build: ./backend
    container_name: nvr-backend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - /run/nvr:/backend
      - ~/creds:/creds
    expose:
      - '5000'
    network_mode: host

  frontend:
    build:
      context: ./frontend
      args:
        NVR_CLIENT_URL: https://nvr.miem.hse.ru
    container_name: nvr-frontend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - /usr/share/nginx/html:/frontend/dist
    network_mode: host

