version: '3'

services:
  redis:
    image: redis
    container_name: nvr-redis
    restart: always
    expose:
      - '6379'

  backend:
    depends_on:
      - redis
    build: ./backend
    container_name: nvr-backend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
    expose:
      - '5000'
      - '5001'
      - '5002'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: nvr-frontend
    restart: always
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
    ports:
      - '8080:80'