version: '3'

services:
  redis:
    image: redis
    container_name: nvr-redis
    expose:
      - '6379'
    network_mode: host

  backend:
    depends_on:
      - redis
    build: ./backend
    container_name: nvr-backend
    env_file:
      - .env_nvr
    volumes:
      - ./backend:/backend
      - ~/creds:/creds
    expose:
      - '5000'
    network_mode: host

  fileuploader:
    build: ./fileuploader
    container_name: fileuploader
    volumes:
      - ./fileuploader:/fileuploader
      - ~/creds:/creds
    expose:
      - '5005'
    network_mode: host

  frontend:
    build:
      context: ./frontend
      args:
        NVR_CLIENT_URL: https://nvr.miem.hse.ru
    container_name: nvr-frontend
    env_file:
      - .env_nvr
    volumes:
      - /usr/share/nginx/html:/frontend/dist
    network_mode: host

