"""empty message

Revision ID: 1747fa4860b3
Revises: 53b0e3c3e5d7
Create Date: 2019-11-21 21:25:34.028047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1747fa4860b3'
down_revision = '53b0e3c3e5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tracking_state', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'processing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('processing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'tracking_state')
    # ### end Alembic commands ###
