"""empty message

Revision ID: 4c628761674f
Revises: 0c7fc1a24ec8
Create Date: 2019-10-11 11:37:18.463624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c628761674f'
down_revision = '0c7fc1a24ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
