"""empty message

Revision ID: aaa08463dec8
Revises: 907e7f24e2c3
Create Date: 2019-11-19 00:34:02.577212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa08463dec8'
down_revision = '907e7f24e2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tracking', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'processing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('processing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'tracking')
    # ### end Alembic commands ###
