"""empty message

Revision ID: dc42aa206166
Revises: dd4e9c8d4fb6
Create Date: 2019-11-20 16:54:48.242954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc42aa206166'
down_revision = 'dd4e9c8d4fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tracking_state', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'processing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('processing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'tracking_state')
    # ### end Alembic commands ###
