"""empty message

Revision ID: 0e9dd6124ab0
Revises: ce823c98f83f
Create Date: 2021-03-06 02:11:23.850347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e9dd6124ab0"
down_revision = "ce823c98f83f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.create_unique_constraint(None, "organizations", ["name"])
    op.drop_constraint("rooms_name_key", "rooms", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("rooms_name_key", "rooms", ["name"])
    op.drop_constraint(None, "organizations", type_="unique")
    op.alter_column(
        "organizations", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###
