"""empty message

Revision ID: 10637a268c39
Revises: bce99d8d86ec
Create Date: 2021-02-22 23:00:44.560199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10637a268c39'
down_revision = 'bce99d8d86ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('organizations')
    # ### end Alembic commands ###
