"""empty message

Revision ID: 122390c96dc2
Revises: 503dd2c64e16
Create Date: 2020-09-09 12:35:24.794184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122390c96dc2'
down_revision = '503dd2c64e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_records')
    # ### end Alembic commands ###
