"""empty message

Revision ID: 2cf749d1c1e4
Revises: 1f0c584351d9
Create Date: 2020-01-27 12:15:10.774105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf749d1c1e4'
down_revision = '1f0c584351d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streams')
    # ### end Alembic commands ###
