"""empty message

Revision ID: 4d8cdc4c7a09
Revises: 122390c96dc2
Create Date: 2020-10-15 00:59:17.451705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d8cdc4c7a09"
down_revision = "122390c96dc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "users", ["api_key"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "last_login")
    # ### end Alembic commands ###
