"""empty message

Revision ID: 503dd2c64e16
Revises: ca7e32f45032
Create Date: 2020-09-01 22:21:03.279425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "503dd2c64e16"
down_revision = "ca7e32f45032"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("error", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "error")
    # ### end Alembic commands ###
