"""empty message

Revision ID: 6d18b8655e19
Revises: dd963660951b
Create Date: 2020-03-29 15:19:19.488935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d18b8655e19'
down_revision = 'dd963660951b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('streaming_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'streaming_url')
    # ### end Alembic commands ###
