"""empty message

Revision ID: 6e516be39982
Revises: 219a462be2e3
Create Date: 2021-03-17 15:07:36.548592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e516be39982"
down_revision = "219a462be2e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.add_column("users", sa.Column("_role", sa.String(length=50), nullable=True))
    op.create_foreign_key(None, "users", "roles", ["_role"], ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "_role")
    op.drop_table("roles")
    # ### end Alembic commands ###
