"""empty message

Revision ID: 87878fc88046
Revises: 481da3e19ef3
Create Date: 2020-02-24 23:44:29.187437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87878fc88046'
down_revision = '481da3e19ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('auto_control', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('audio', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('merge', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('port', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('rtsp', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('tracking', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'tracking')
    op.drop_column('sources', 'rtsp')
    op.drop_column('sources', 'port')
    op.drop_column('sources', 'merge')
    op.drop_column('sources', 'audio')
    op.drop_column('rooms', 'auto_control')
    # ### end Alembic commands ###
