"""empty message

Revision ID: a5e67a6a944b
Revises: 8e254effa38b
Create Date: 2021-03-18 23:14:02.835252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e67a6a944b'
down_revision = '8e254effa38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['_role_id'], ['id'])
    op.drop_column('users', '_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', '_role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
