"""empty message

Revision ID: b0ae2dcdb372
Revises: c63b3558773d
Create Date: 2020-06-29 17:15:35.969692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ae2dcdb372'
down_revision = 'c63b3558773d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    # ### end Alembic commands ###
