"""empty message

Revision ID: b1d97f35b0c1
Revises: 4d8cdc4c7a09
Create Date: 2020-10-22 19:37:59.333878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d97f35b0c1'
down_revision = '4d8cdc4c7a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('time_editing', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'time_editing')
    op.drop_column('sources', 'external_id')
    # ### end Alembic commands ###
