"""empty message

Revision ID: bce99d8d86ec
Revises: 205e9569ea2a
Create Date: 2021-01-29 01:51:18.794395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bce99d8d86ec"
down_revision = "205e9569ea2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("banned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "banned")
    # ### end Alembic commands ###
