"""empty message

Revision ID: c228c2073ceb
Revises: 6d18b8655e19
Create Date: 2020-03-29 15:21:15.115216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c228c2073ceb'
down_revision = '6d18b8655e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('stream_url', sa.String(length=300), nullable=True))
    op.drop_column('rooms', 'streaming_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('streaming_url', mysql.VARCHAR(collation='utf8_bin', length=300), nullable=True))
    op.drop_column('rooms', 'stream_url')
    # ### end Alembic commands ###
