"""empty message

Revision ID: c63b3558773d
Revises: 6519b50e0a2c
Create Date: 2020-06-27 17:26:30.920909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c63b3558773d"
down_revision = "6519b50e0a2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint(None, "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
