"""empty message

Revision ID: ca7e32f45032
Revises: b0ae2dcdb372
Create Date: 2020-09-01 00:31:04.403202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca7e32f45032"
down_revision = "b0ae2dcdb372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_16679_room_id", table_name="channels")
    op.drop_constraint("channels_ibfk_1", "channels", type_="foreignkey")
    op.create_foreign_key(None, "channels", "rooms", ["room_id"], ["id"])
    op.add_column(
        "records", sa.Column("drive_file_url", sa.String(length=200), nullable=True)
    )
    op.add_column("rooms", sa.Column("ruz_id", sa.Integer(), nullable=True))
    op.drop_index("idx_16696_name", table_name="rooms")
    op.create_unique_constraint(None, "rooms", ["name"])
    op.drop_index("idx_16712_room_id", table_name="sources")
    op.drop_constraint("sources_ibfk_1", "sources", type_="foreignkey")
    op.create_foreign_key(None, "sources", "rooms", ["room_id"], ["id"])
    op.drop_index("idx_16728_api_key", table_name="users")
    op.drop_index("idx_16728_email", table_name="users")
    op.create_unique_constraint(None, "users", ["api_key"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("idx_16728_email", "users", ["email"], unique=True)
    op.create_index("idx_16728_api_key", "users", ["api_key"], unique=True)
    op.drop_constraint(None, "sources", type_="foreignkey")
    op.create_foreign_key(
        "sources_ibfk_1",
        "sources",
        "rooms",
        ["room_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.create_index("idx_16712_room_id", "sources", ["room_id"], unique=False)
    op.drop_constraint(None, "rooms", type_="unique")
    op.create_index("idx_16696_name", "rooms", ["name"], unique=True)
    op.drop_column("rooms", "ruz_id")
    op.drop_column("records", "drive_file_url")
    op.drop_constraint(None, "channels", type_="foreignkey")
    op.create_foreign_key(
        "channels_ibfk_1",
        "channels",
        "rooms",
        ["room_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.create_index("idx_16679_room_id", "channels", ["room_id"], unique=False)
    # ### end Alembic commands ###
