"""empty message

Revision ID: ce823c98f83f
Revises: 8316f4f289c1
Create Date: 2021-03-01 01:45:37.124166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce823c98f83f"
down_revision = "8316f4f289c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "tracking_state")
    op.drop_column("rooms", "tracking_source")
    op.drop_column("rooms", "stream_url")
    op.drop_column("sources", "tracking")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column(
            "tracking",
            sa.VARCHAR(length=200),
            server_default=sa.text("NULL::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "stream_url",
            sa.VARCHAR(length=300),
            server_default=sa.text("NULL::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "tracking_source",
            sa.VARCHAR(length=100),
            server_default=sa.text("NULL::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column("tracking_state", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
