"""empty message

Revision ID: cf578317c711
Revises: 2ebb82619e3b
Create Date: 2020-11-18 23:45:48.592325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cf578317c711"
down_revision = "2ebb82619e3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channels")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "resource_id",
            sa.VARCHAR(length=100),
            server_default=sa.text("NULL::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("room_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "modified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="channels_room_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="idx_16679_primary"),
    )
    # ### end Alembic commands ###
