"""empty message

Revision ID: dd4e9c8d4fb6
Revises: aaa08463dec8
Create Date: 2019-11-19 23:20:54.912846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd4e9c8d4fb6'
down_revision = 'aaa08463dec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tracking_state', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tracking', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'tracking_state')
    # ### end Alembic commands ###
