"""empty message

Revision ID: fcee913329c9
Revises: 4090cf7b2bc6
Create Date: 2020-11-25 12:29:57.504273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcee913329c9'
down_revision = '4090cf7b2bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('online_rooms', sa.Column('drive', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('online_rooms', 'drive')
    # ### end Alembic commands ###
