"""empty message

Revision ID: 1526f2dc9461
Revises: 1c5b0307eebf
Create Date: 2020-02-22 21:29:20.092059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1526f2dc9461'
down_revision = '1c5b0307eebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('main_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('screen_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('sound_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('tracking_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'tracking_source')
    op.drop_column('rooms', 'sound_source')
    op.drop_column('rooms', 'screen_source')
    op.drop_column('rooms', 'main_source')
    # ### end Alembic commands ###
