"""empty message

Revision ID: 1c5b0307eebf
Revises: 2cf749d1c1e4
Create Date: 2020-02-21 12:46:33.857488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c5b0307eebf'
down_revision = '2cf749d1c1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'tracking_source')
    op.drop_column('rooms', 'free')
    op.drop_column('rooms', 'main_source')
    op.drop_column('rooms', 'sound_source')
    op.drop_column('rooms', 'screen_source')
    op.add_column('sources', sa.Column('audio', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('merge', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('port', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('rtsp', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('tracking', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'tracking')
    op.drop_column('sources', 'rtsp')
    op.drop_column('sources', 'port')
    op.drop_column('sources', 'merge')
    op.drop_column('sources', 'audio')
    op.add_column('rooms', sa.Column('screen_source', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.add_column('rooms', sa.Column('sound_source', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.add_column('rooms', sa.Column('main_source', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.add_column('rooms', sa.Column('free', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('tracking_source', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    # ### end Alembic commands ###
