"""empty message

Revision ID: 231247ff7a04
Revises: f5db7014e848
Create Date: 2020-03-24 20:28:07.122518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '231247ff7a04'
down_revision = 'f5db7014e848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pid_unique', table_name='streams')
    op.drop_table('streams')
    op.drop_table('user_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_records',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('drive_file_url', mysql.VARCHAR(collation='utf8_bin', length=300), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('streams',
    sa.Column('url', mysql.VARCHAR(collation='utf8_bin', length=250), nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('url'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('pid_unique', 'streams', ['pid'], unique=True)
    # ### end Alembic commands ###
