"""empty message

Revision ID: 469ac8ea5dc7
Revises: c5e9726bcc90
Create Date: 2019-09-22 14:15:10.395567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469ac8ea5dc7'
down_revision = 'c5e9726bcc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'calendar',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rooms', 'drive',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('rooms', 'chosenSound')
    op.drop_column('rooms', 'status')
    op.add_column('sources', sa.Column('main_cam', sa.Boolean(), nullable=True))
    op.alter_column('sources', 'tracking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('sources', 'mainCam')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('sources', sa.Column('mainCam', sa.BOOLEAN(), nullable=False))
    op.alter_column('sources', 'tracking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('sources', 'main_cam')
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.add_column('rooms', sa.Column('chosenSound', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rooms', 'drive',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('rooms', 'calendar',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
