"""empty message

Revision ID: 481da3e19ef3
Revises: 1526f2dc9461
Create Date: 2020-02-24 00:24:37.242058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481da3e19ef3'
down_revision = '1526f2dc9461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('auto_control', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'auto_control')
    # ### end Alembic commands ###
