"""empty message

Revision ID: 4951939c4d57
Revises: d3bd71078459
Create Date: 2019-07-18 21:46:45.759398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4951939c4d57'
down_revision = 'd3bd71078459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
