"""empty message

Revision ID: 71e237baafa2
Revises: eb2e9fc5f32d
Create Date: 2019-07-08 23:08:25.365638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e237baafa2'
down_revision = 'eb2e9fc5f32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
