"""empty message

Revision ID: 74ed9dbb828a
Revises: 4951939c4d57
Create Date: 2019-09-17 00:58:30.777080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ed9dbb828a'
down_revision = '4951939c4d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('processing', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.drop_column('rooms', 'processing')
    # ### end Alembic commands ###
