"""empty message

Revision ID: 8e828ac60d8c
Revises: 469ac8ea5dc7
Create Date: 2019-09-22 15:05:56.037958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e828ac60d8c'
down_revision = '469ac8ea5dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('chosen_sound', sa.String(length=100), nullable=True))
    op.alter_column('rooms', 'calendar',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=True)
    op.alter_column('rooms', 'drive',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=True)
    op.alter_column('rooms', 'free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('rooms', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=100),
               nullable=False)
    op.alter_column('rooms', 'processing',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('rooms', 'timestamp',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('rooms', 'chosenSound')
    op.add_column('sources', sa.Column('main_cam', sa.Boolean(), nullable=True))
    op.alter_column('sources', 'tracking',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('sources', 'mainCam')
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=False)
    op.add_column('sources', sa.Column('mainCam', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('sources', 'tracking',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('sources', 'main_cam')
    op.add_column('rooms', sa.Column('chosenSound', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False))
    op.alter_column('rooms', 'timestamp',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('rooms', 'processing',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('rooms', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=100),
               nullable=True)
    op.alter_column('rooms', 'free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('rooms', 'drive',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=False)
    op.alter_column('rooms', 'calendar',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=False)
    op.drop_column('rooms', 'chosen_sound')
    # ### end Alembic commands ###
