"""empty message

Revision ID: 8f0b730d464e
Revises: 1747fa4860b3
Create Date: 2020-01-15 10:20:11.379473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f0b730d464e'
down_revision = '1747fa4860b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('main_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('sound_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('tracking_source', sa.String(length=100), nullable=True))
    op.drop_column('rooms', 'chosen_sound')
    op.drop_column('sources', 'tracking')
    op.drop_column('sources', 'sound')
    op.drop_column('sources', 'main_cam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('main_cam', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('sound', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.add_column('sources', sa.Column('tracking', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('chosen_sound', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.drop_column('rooms', 'tracking_source')
    op.drop_column('rooms', 'sound_source')
    op.drop_column('rooms', 'main_source')
    # ### end Alembic commands ###
