"""empty message

Revision ID: 907e7f24e2c3
Revises: 4c628761674f
Create Date: 2019-10-11 22:48:14.986329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907e7f24e2c3'
down_revision = '4c628761674f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
