"""empty message

Revision ID: c5e9726bcc90
Revises: dd4a5a699a2c
Create Date: 2019-09-22 14:12:51.920202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e9726bcc90'
down_revision = 'dd4a5a699a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('chosen_sound', sa.String(length=100), nullable=True))
    op.alter_column('rooms', 'free',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rooms', 'processing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rooms', 'timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rooms', 'chosenSound')
    op.drop_column('rooms', 'status')
    op.add_column('sources', sa.Column('main_cam', sa.Boolean(), nullable=False))
    op.drop_column('sources', 'mainCam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('mainCam', sa.BOOLEAN(), nullable=False))
    op.drop_column('sources', 'main_cam')
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.add_column('rooms', sa.Column('chosenSound', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('rooms', 'timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'processing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rooms', 'free',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('rooms', 'chosen_sound')
    # ### end Alembic commands ###
