"""empty message

Revision ID: c7543c97a602
Revises: 231247ff7a04
Create Date: 2020-03-24 22:33:25.419548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7543c97a602'
down_revision = '231247ff7a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'done')
    # ### end Alembic commands ###
