"""empty message

Revision ID: ea7e4a46ac7a
Revises: 87878fc88046
Create Date: 2020-02-28 00:35:33.213930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7e4a46ac7a'
down_revision = '87878fc88046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('auto_control', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('main_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('screen_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('sound_source', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('tracking_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'tracking_source')
    op.drop_column('rooms', 'sound_source')
    op.drop_column('rooms', 'screen_source')
    op.drop_column('rooms', 'main_source')
    op.drop_column('rooms', 'auto_control')
    # ### end Alembic commands ###
