"""empty message

Revision ID: eb2e9fc5f32d
Revises: 05d2d3631676
Create Date: 2019-07-08 23:07:55.692778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2e9fc5f32d'
down_revision = '05d2d3631676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('free', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.drop_column('rooms', 'free')
    # ### end Alembic commands ###
